name: Greeter
description: Composite Action to greet someone

on:
  workflow_dispatch:


runs:
  using: composite
  steps:
        
    - name: greet
      run: echo "Hello world"
      shell: bash

    - name: greet2
      run: echo "Hello world 2"
      shell: bash
