name: Greeter
description: Composite Action to greet someone

on:
  workflow_dispatch:

inputs:
  CLEANUP:
    required: true
    default: true
    description: who to greet

runs:
  using: composite
  steps:
    - name: Deploy enclave 
      env:
        CLEANUP: '${{ inputs.CLEANUP }}'
      run: |
        if [ "$CLEANUP" = "true" ]; then
          echo "true"
        else
          echo "false !!! $CLEANUP" 
        fi
      shell: bash

        
    - name: greet
      run: echo "Hello world"
      shell: bash

