name: Greeter
description: Composite Action to greet someone

on:
  workflow_dispatch:

inputs:
  CLEANUP:
    required: true
    default: true
    description: who to greet

runs:
  using: composite
  steps:
    - name: Define secret
      shell: bash
      run: |
        echo "::add-mask::${{inputs.CLEANUP}}"
        echo "${{ inputs.CLEANUP }}"
      env:
        
        
    - name: greet
      run: echo "Hello world"
      shell: bash

