name: Greeter
description: Composite Action to greet someone

on:
  workflow_dispatch:

# inputs:
#   who-to-greet:
#     required: false
#     default: World
#     description: who to greet

runs:
  using: composite
  steps:
    - name: setup python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: greet
      run: echo "Hello world"
      shell: bash

    - name: greet2
      run: echo "Hello world 2"
      shell: bash
