name: Greeter
description: Composite Action to greet someone

on:
  workflow_dispatch:

inputs:
  CLEANUP:
    required: true
    default: true
    description: who to greet

runs:
  using: composite
  steps:
    - name: Define secret
      shell: bash
      run: |
        CLEANUP="$(echo ${{inputs.CLEANUP}})"
        echo "::add-mask::$CLEANUP"
        echo "${{ inputs.CLEANUP }}"
              
    - name: greet
      run: echo "Hello world"
      shell: bash

