# # This is a basic workflow to help you get started with Actions

name: build

on:
  push:
    branches: [main]

jobs:
  # start ec2 instances (future)
  # prepare env and build_docker image
  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run
        run: echo "Run !!"

