# # This is a basic workflow to help you get started with Actions

name: CI

on:
  # pull_request:
  #   branches: [develop]
  push:
    branches: [main]
    paths:
      - 'test.py'
      - '*/**'

jobs:
  # start ec2 instances (future)
  # prepare env and build_docker image
  build_docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          python3 test.py

      - id: composite
        name: Calling composite action
        uses: TanapholSU/TestAction/.github/workflows/test.yml@main
