# # This is a basic workflow to help you get started with Actions

name: CI

on:
  # pull_request:
  #   branches: [develop]
  push:
    branches: [dev]
    paths:
      - '*'
      - '*/**'

jobs:
  # start ec2 instances (future)
  # prepare env and build_docker image
  build_docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.4' 

      - name: Run
        run: |
          python3 test.py
      
