permissions:
  Administration: write 

name: test
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLEANUP: true
    steps:
      - name: echo
        run: |
          if [ "$CLEANUP" = "true" ]; then
            echo "cleanup is true"
          else
            echo "cleanup is false"
          fi
        shell: bash




