
name: test
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLEANUP: false
    steps:
      - name: echo
        run: |
          if [ "1" -eq "1"]; then
            echo "cleanup is true"
          else
            echo "cleanup is false $CLEANUP"
          fi
        shell: bash




