
name: test
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLEANUP: "false"
    steps:
      - name: echo
        run: |
          if [ 0 ]; then
            echo "cleanup is true $CLEANUP"
          else
            echo "cleanup is false $CLEANUP"
          fi
        shell: bash




