name: Release
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: 
      - completed


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "hello world"
