
name: test
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLEANUP: "false"
    steps:
      - uses: actions/checkout@v4

      - name: test action
        uses: ./.github/actions/prepare_env
        with:
          CLEANUP: true




