permissions: write-all

name: test
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/TanapholSU/TestAction/actions/runners/registration-token

        shell: bash


